package time.no.see.mapper.resources;

import java.util.List;

import time.no.see.model.beans.resources.Sys_Resource;

public interface Sys_ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int insert(Sys_Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int insertSelective(Sys_Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    Sys_Resource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int updateByPrimaryKeySelective(Sys_Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int updateByPrimaryKey(Sys_Resource record);

	List<Sys_Resource> selectByParent_Id(long l);
}