package time.no.see.mapper.role;

import time.no.see.model.beans.role.Sys_Role;

public interface Sys_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int insert(Sys_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int insertSelective(Sys_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    Sys_Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int updateByPrimaryKeySelective(Sys_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Sat Jul 13 14:51:05 CST 2019
     */
    int updateByPrimaryKey(Sys_Role record);
}